### PR TITLE
Add the ability to add custom receivers

### PR DESCRIPTION
**Pull request by justmoon**
Allows users to create receivers of the form `alice+myreceiver@example.com`. Inspired by [Gmail's similar feature](http://fieldguide.gizmodo.com/how-to-use-the-infinite-number-of-email-addresses-gmail-1609458192).

Currently, the only configuration per receiver is a webhook URI, but it's easy to imagine all sorts of other options/customization in the future.

It's also possible that we could make the default receiver (`alice@example.com`) configurable in the same way.

screenshot from 2017-01-16 12-19-48

This PR is still WIP and not ready to merge.

### CODE REVIEW

**Comment by sharafian** [comment]
Do the webhooks allow you to provide a payment request when someone queries `/receiver`, or do they just notify when a payment has been received?

**Comment by justmoon** [comment]
@sharafian Right now, it lets you return a boolean. If `true` the transfer is accepted, if `false` it's rejected. After seeing your KEP PR, I would probably change that to return an error in the rejection case.

Not sure what you mean by returning a payment request - the webhook is triggered when a KEP payment comes in.

**Comment by vhpoet** [comment]
@justmoon do we still need this?

**Comment by justmoon** [comment]
Eventually, maybe, but for now we'll probably use something like [koa-ilp](https://github.com/justmoon/koa-ilp), i.e. have a plugin embedded in the app we're trying to ILP-enable.

Closing this for now.

**Pull request closed without merging**
