### PR TITLE
chore: .gitignore, .dockerignore, docs

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
node 8 comes with npm 5, which supports lock files and makes `npm install` much faster, so we no longer have a strong reason to use yarn.

**Comment by michielbdejong** [comment]
The tests fail with:
```sh
 Error: Please install sqlite3 package manually
```

Sounds like sqlite3 is "locked" to MacOS and then fails on Ubuntu?

@dappelt I'll see if I get a different package-lock.json on Ubuntu, but if that's the case, then maybe we want to ship both of them?

**Comment by michielbdejong** [comment]
Updated with package-lock.json for Docker's `node:8-slim` image, which is itself based on Debian Jessie. This seems to work better, because it does seem to work for on Darwin/Mac/OSX.

**Comment by dappelt** [comment]
> I'll see if I get a different package-lock.json on Ubuntu, but if that's the case, then maybe we want to ship both of them?

I would assume the contents of package-lock.json are independent of the operating system you used for the build. Did you find otherwise?

**Comment by michielbdejong** [comment]
> Did you find otherwise?

yeah, the tests are failing

**Comment by dappelt** [comment]
Sure, the test cases fail, but do they fail because package-lock.json contains platform-specific dependencies or due to some other reason? 

To come back to your original question, I don't think package-lock.json is platform-specific.

**Comment by michielbdejong** [comment]
yarn.lock was already removed in another commit.

**Comment by michielbdejong** [comment]
Weird, all this changes in the eyes of CircleCI is the node version (8 instead of 7), yet still it seems to consistently break the connector_first integration test: https://circleci.com/gh/interledgerjs/ilp-kit/tree/mj-node-8

**Comment by michielbdejong** [comment]
It seems our connector_first integration test is incompatible with node 8. [This change](https://github.com/interledgerjs/ilp-kit/commit/425504521467710e53424b2806f9bc8ee7812280) makes [these tests](https://circleci.com/gh/interledgerjs/ilp-kit/tree/mj-node-8) pass.

@sentientwaffle any idea what's going on here?

**Comment by sentientwaffle** [comment]
I think the connector_first test failure is a race condition that I introduced when fixing the ilp-kit test failure. I'm working on a fix.

**Comment by michielbdejong** [comment]
I triggered 3 new  builds on the master branch to test that theory: https://circleci.com/gh/interledgerjs/ilp-kit/tree/master

**Pull request merged**
