### PR TITLE
Docs: add instructional gist to repo

### PR DESCRIPTION
**Pull request by sharafian**
From https://gist.github.com/sharafian/c85e779d2544ba1cb136476acfd3adc2
Resubmit on https://github.com/interledgerjs/ilp-kit/pull/73 , addressed issues.

### CODE REVIEW

**Comment by vhpoet** [comment]
The repo already has a readme file with instructions on setting up and running. Wouldn't it be confusing to have two docs? Can we merge the readme and this somehow?

**Comment by sharafian** [comment]
@vhpoet maybe the README could be changed to explain what `ilp-kit` is, why you'd want to run it, etc. Then it can have a link to the setup instructions/the wiki

**Comment by vhpoet** [comment]
LGTM

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
