### PR TITLE
Reenable api unit tests

### PR DESCRIPTION
**Pull request by michielbdejong**
Let's see if circle now runs all unit tests that have not been `it.skip`'ed

### CODE REVIEW

**Comment by michielbdejong** [comment]
@dappelt Any idea why 'ci/circleci — Waiting for status to be reported' is taking so long to complete?

**Comment by dappelt** [comment]
It looks like there was no build triggered at CircleCI at all. @emschwartz any idea why this might be the case?

**Comment by michielbdejong** [comment]
Ah, probably because I created the branch on my fork. Let me create a branch for it on the org.

**Comment by michielbdejong** [comment]
Continued in #216

**Pull request closed without merging**
