### PR TITLE
feat: add .dockerignore file

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
@dappelt can you test if this resolves the dependency-rebuild problem you reported on slack?

**Comment by dappelt** [comment]
Should the [Dockerfile](https://github.com/interledgerjs/ilp-kit/blob/master/Dockerfile) be changed as well:

1) In order to not have to download all the dependencies each time the image is build, I propose to base the image not `node:7-slim`, but the recommended image `node:7`.
2) It should be enough to run `npm install`, without running specifically running `npm rebuild` or `npm run rebuild`, since the later commands are executed as part of `npm install`.

**Comment by michielbdejong** [comment]
Even node:7 would need the addition of postgres etc, so we might as well stick with node:7-slim and keep python etc in that apt-get as well.

the postinstall step of `npm install` is skipped because npm install is run as root, that's the same on https://github.com/interledgerjs/five-bells-integration-test/blob/master/Dockerfile#L65-L72

**Comment by dappelt** [comment]
Ok, convinced. Let's keep the Dockerfile.

**Pull request merged**
