### PR TITLE
Combination PR for ilp-kit 3.0.0

### PR DESCRIPTION
**Pull request by michielbdejong**
Depends on:

* [ ] [`mj-test-dj-ilqp` branch in five-bells-ledger](https://github.com/interledgerjs/five-bells-ledger/pull/424) - mainly Stefan's changes there
* [x] [`mj-test-dj-ilqp` branch in ilp](https://github.com/interledgerjs/ilp/pull/104) DJ's changes and a comment block
* [ ] [`mj-test-dj-ilqp` branch in ilp-routing](https://github.com/interledgerjs/ilp-routing/pull/45) - allow routes without curves in the tables
* [x] [`mj-test-dj-ilqp` branch in ilp-core](https://github.com/interledgerjs/ilp-core/pull/89) - not sure if this is actually still used?
* [ ] [`mj-test-dj-ilqp` branch in ilp-connector](https://github.com/interledgerjs/ilp-connector/pull/350) - mainly DJ's changes, and configurable broadcast/store curves
* [x] [`mj-test-dj-ilqp` branch in five-bells-integration-test](https://github.com/interledgerjs/five-bells-integration-test/pull/77) mainly DJ's changes, and remove hold account checks.

### CODE REVIEW

**Comment by michielbdejong** [comment]
Currently seeing a problem in integration tests:
```
ilp-kit[Wallet1] [api]   InternalServerError: InvalidLiquidityCurveError: Curve x-coordinates must strictly increase in series points:[[0,0],[0,0],[100000000000000,0]]
```
should be easy to check for, probably in ilp-routing.

**Comment by michielbdejong** [comment]
All tests passing now, except for the skipped tests mentioned above.

**Comment by michielbdejong** [comment]
route broadcasts will now have binary curve data, so that's a breaking change.

**Comment by sentientwaffle** [comment]
Why are the plugin tests skipped? https://github.com/interledgerjs/ilp-plugin-bells/pull/127 passes without any skips.

**Comment by michielbdejong** [comment]
> Why are the plugin tests skipped?

Yes, I saw, I'll remove those `.skip`'s again.

**Comment by michielbdejong** [comment]
Changed version back to only 2.1.0, because we found a way to make connector-to-connector messaging backwards compatible with 2.0.*

**Comment by michielbdejong** [comment]
plan keeps changing :) current ilp-kit relies on JSON remote quoting, which is removed in this PR, which is why this is breaking.

**Comment by michielbdejong** [comment]
Nothing left to commit here, closing.

**Pull request closed without merging**
